- name: change prometheus configurations
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/systemd/system/prometheus.service

- name: restart service
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
